# Numpy - Library to handle arrays.
- statically typed (element types can't be mixed or altered).
- non resizeble (can't append or remove elements).
- much faster than pythons dynamically typed lists.
- supports use of vector operations.


## Create arrays

In [6]:
import numpy as np

my_array = np.array([5, 2, 6, 8])
my_array.dtype # visa/bestäm datatyp



dtype('int32')

In [10]:
a2 = np.random.random(20)
a3 = np.random.randint(10, 20, 10)
a3


array([14, 18, 16, 18, 11, 16, 12, 15, 12, 13])

In [12]:
a4 = np.zeros(10)
a5 = np.ones(10)
a5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
a6 = np.linspace(0, 10, 100)
a7 = np.arange(0, 10, 0.2)
a6

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Vectorized operations

In [21]:
x = [2, 4, 7, 1, 7, 3, 2, 5, 2]
x * 2

[2, 4, 7, 1, 7, 3, 2, 5, 2, 2, 4, 7, 1, 7, 3, 2, 5, 2]

In [18]:
y = [value * 2 for value in x]
y

[4, 8, 14, 2, 14, 6, 4, 10, 4]

In [20]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [23]:
np.sqrt(x)

array([1.41421356, 2.        , 2.64575131, 1.        , 2.64575131,
       1.73205081, 1.41421356, 2.23606798, 1.41421356])

In [12]:
import matplotlib as plt
import numpy as np

x = np.linspace(-10, 10, 1000)
np.sin(x * 2 * np.pi) * 10 + 1
plt.plot(x, y)


AttributeError: module 'matplotlib' has no attribute 'plot'

In [11]:
a = np.array([2, 4, 7, 1, 7])
b = np.array([3, 2, 5, 2, 6])

np.sqrt(a**2 + b**2)

array([3.60555128, 4.47213595, 8.60232527, 2.23606798, 9.21954446])

In [9]:
a.shape


(5,)

# Array indexing & slicing
- Indexing and slicing works just as we are used to from Python lists.
- However, we can also use a list of indexes when indexing a numpy array.
- Boolean mask / indexing can be used to filter through data in arrays.

In [14]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [18]:
x[[5, 0, 1, 0, -1]]

array([3, 2, 4, 2, 2])

In [21]:
x == 2

array([ True, False, False, False, False, False,  True, False,  True])

In [25]:
# Filtering using a list of indexes:
x[[0, 2, 0, -1, 1]]

array([2, 7, 2, 2, 4])

In [24]:
# Boolean indexing:
x[[False, False,  True, False,  True, False, False,  True, False]]

array([7, 7, 5])

In [23]:
# Boolean mask can be created using comparison operators on numpy arrays
x >= 5

array([False, False,  True, False,  True, False, False,  True, False])

In [26]:
# Put togeher looks like this 
x[x >= 5]

array([7, 7, 5])

## Aggregation methods
An aggregation method is a method that takes a list/array of values and by doing some calculations, returning a single value.

In [27]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [29]:
print(f"{x.sum() = }") # summan av alla värden
print(f"{x.min() = }") # minsta värdet
print(f"{x.max() = }") # högsta värdet
print(f"{x.mean() = }") # medelvärdet


x.sum() = 33
x.min() = 1
x.max() = 7
x.mean() = 3.6666666666666665
